import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import AdBlock from "../../components/Ads/AdBlock";
import AdSidebar from "../../components/Ads/AdSidebar";
import { fetchNews } from "../../utils/fetch";
import classes from "./index.module.css";
import ReactMarkdown from "react-markdown";

export default function NewsDetail() {
  const router = useRouter();
  const { slug } = router.query;
  const [article, setArticle] = useState(null);

  useEffect(() => {
    async function getArticle() {
      try {
        const articles = await fetchNews();
        const found = articles.find((item) => item.slug === slug);
        setArticle(found || null);
      } catch (err) {
        console.error("Failed to load article:", err);
        setArticle(null);
      }
    }

    if (slug) getArticle();
  }, [slug]);

  if (!article) return <p className={classes.loading}>Loading article...</p>;

  return (
    <div className={classes.pageWrapper}>
      <div className={classes.newsP}>
        <div className={classes.header}>
          <h1 className={classes.title}>{article.title}</h1>
          {/* Top Ad */}
          <AdBlock
            adSlot="1234567890"
            className={`${classes.adBlock} ${classes.adTop}`}
          />
          {article.image && (
            <img
              src={article.image}
              alt={article.title}
              className={classes.newsImage}
            />
          )}
          <p className={classes.newsSummary}>{article.summary}</p>
          {article.publishedAt && (
            <div className={classes.metadata}>
              <span className={classes.date}>
                {new Date(article.publishedAt).toLocaleDateString()}
              </span>
            </div>
          )}
        </div>

        <div className={classes.newsContent}>
          <ReactMarkdown>{article.content}</ReactMarkdown>
        </div>
        {/* Bottom Ad */}
        <AdBlock
          adSlot="2345678901"
          className={`${classes.adBlock} ${classes.adBottom}`}
        />
        {article.isGenerated && (
          <p className={classes.generatedLabel}>
            ⚡ This article was generated by AI
          </p>
        )}
      </div>
      <AdSidebar adSlots={["3456789012", "4567890123", "5678901234"]} />
    </div>
  );
}
